services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: super‑duper‑secret‑key
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      # this host name “postgres” resolves only inside the Docker network:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cloudbuilder
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: on-failure

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - tls_cert
      - tls_key
    restart: on-failure

secrets:
  tls_cert:
    file: ./nginx/certs/server.crt
  tls_key:
    file: ./nginx/certs/server.key

volumes:
  postgres_data:
